import { processSharedUtil } from './infra/process.shared.util'
import { zipSharedUtil } from './util/zip.shared.util'
import { ExtendedJoi, Joi } from './validation/joi/joi.extensions'
import {
  anyObjectSchema,
  anySchema,
  arraySchema,
  binarySchema,
  booleanSchema,
  dateStringSchema,
  emailSchema,
  idSchema,
  integerSchema,
  ipAddressSchema,
  numberSchema,
  objectSchema,
  SEM_VER_PATTERN,
  semVerSchema,
  stringSchema,
  unixTimestampSchema,
  userAgentSchema,
  utcOffsetSchema,
  verSchema,
} from './validation/joi/joi.shared.schemas'
import { JoiValidationError } from './validation/joi/joi.validation.error'
import { JoiValidationResult, joiValidationService } from './validation/joi/joi.validation.service'

export {
  // todo: in progress, not exported yet
  // GotOptions,
  // GotResponse,
  // gotService,
  // getDebug,
  // LUXON_ISO_DATE_FORMAT,
  // localDateUtil,
  // localTimeUtil,
  JoiValidationError,
  JoiValidationResult,
  joiValidationService,
  Joi,
  ExtendedJoi,
  booleanSchema,
  stringSchema,
  numberSchema,
  integerSchema,
  dateStringSchema,
  arraySchema,
  binarySchema,
  objectSchema,
  anySchema,
  anyObjectSchema,
  idSchema,
  unixTimestampSchema,
  verSchema,
  emailSchema,
  SEM_VER_PATTERN,
  semVerSchema,
  userAgentSchema,
  utcOffsetSchema,
  ipAddressSchema,
  processSharedUtil,
  zipSharedUtil,
}
