on:
  push:
    branches: [master, docs]

env:
  NODE_OPTIONS: --max-old-space-size=3200

jobs:
  docs-job:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v3, with: { persist-credentials: false } }
      - { uses: actions/setup-node@v3, with: { node-version: 18, cache: 'yarn' } }
      - run: yarn --frozen-lockfile

      - name: docs-build
        run: yarn docs-build

      - name: publish docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          force_orphan: true
          commit_message: 'deploy docs [skip ci]'
          # publish_branch: gh-pages
